In [2]:
import numpy as np

sentence = "What are the symptoms of diabetes?"
tokens = sentence.split()

seq_len = len(tokens)
d_model = 8
d_k = 4

np.random.seed(42)

X = np.random.randn(seq_len, d_model)

W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)

Q = np.dot(X, W_Q)
K = np.dot(X, W_K)
V = np.dot(X, W_V)

scores = np.dot(Q, K.T) / np.sqrt(d_k)

def softmax(x):
    x = x - np.max(x, axis=1, keepdims=True)
    e = np.exp(x)
    return e / np.sum(e, axis=1, keepdims=True)

attention = softmax(scores)

output = np.dot(attention, V)

print("tokens:", tokens)
print("attention:")
print(np.round(attention, 3))

print("output:")
print(np.round(output, 3))

tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes?']
attention:
[[0.    0.    0.    1.    0.    0.   ]
 [0.949 0.    0.051 0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.   ]
 [0.948 0.    0.    0.052 0.    0.   ]
 [0.96  0.    0.039 0.    0.    0.   ]
 [0.99  0.    0.001 0.009 0.    0.   ]]
output:
[[ 0.416  3.178 -4.023  1.909]
 [ 0.492  4.002 -0.164 -3.637]
 [ 3.157 -2.568  1.238 -2.613]
 [ 0.594  4.557 -0.419 -3.604]
 [ 0.517  4.141 -0.177 -3.694]
 [ 0.601  4.614 -0.256 -3.851]]
